package cn.edu.shu.society.dto;

public class VoteTopicNumberDTO {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.id
     *
     * @mbggenerated Sat Jul 02 18:52:49 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.vote_topic_id
     *
     * @mbggenerated Sat Jul 02 18:52:49 CST 2016
     */
    private Long voteTopicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.vote_topic_vote_number
     *
     * @mbggenerated Sat Jul 02 18:52:49 CST 2016
     */
    private Long voteTopicVoteNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.create_time
     *
     * @mbggenerated Sat Jul 02 18:52:49 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.update_time
     *
     * @mbggenerated Sat Jul 02 18:52:49 CST 2016
     */
    private Long updateTime;


    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public Long getVoteTopicId() {
        return voteTopicId;
    }


    public void setVoteTopicId(Long voteTopicId) {
        this.voteTopicId = voteTopicId;
    }


    public Long getCreateTime() {
        return createTime;
    }


    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }


    public Long getUpdateTime() {
        return updateTime;
    }


    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    public Long getVoteTopicVoteNumber() {
        return voteTopicVoteNumber;
    }

    public void setVoteTopicVoteNumber(Long voteTopicVoteNumber) {
        this.voteTopicVoteNumber = voteTopicVoteNumber;
    }
}