package cn.edu.shu.society.entity;

public class MessageType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.type_name
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_type.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.id
     *
     * @return the value of message_type.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.id
     *
     * @param id the value for message_type.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.user_id
     *
     * @return the value of message_type.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.user_id
     *
     * @param userId the value for message_type.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.type_name
     *
     * @return the value of message_type.type_name
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.type_name
     *
     * @param typeName the value for message_type.type_name
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.create_time
     *
     * @return the value of message_type.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.create_time
     *
     * @param createTime the value for message_type.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_type.update_time
     *
     * @return the value of message_type.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_type.update_time
     *
     * @param updateTime the value for message_type.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}