package cn.edu.shu.society.entity;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_passed
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Boolean isPassed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long messageTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_id
     *
     * @return the value of message.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_id
     *
     * @param userId the value for message.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_passed
     *
     * @return the value of message.is_passed
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Boolean getIsPassed() {
        return isPassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_passed
     *
     * @param isPassed the value for message.is_passed
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setIsPassed(Boolean isPassed) {
        this.isPassed = isPassed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_type_id
     *
     * @return the value of message.message_type_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getMessageTypeId() {
        return messageTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_type_id
     *
     * @param messageTypeId the value for message.message_type_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setMessageTypeId(Long messageTypeId) {
        this.messageTypeId = messageTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_time
     *
     * @return the value of message.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_time
     *
     * @param updateTime the value for message.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}