package cn.edu.shu.society.entity;

public class Response {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.user_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.content
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.message_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column response.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.id
     *
     * @return the value of response.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.id
     *
     * @param id the value for response.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.user_id
     *
     * @return the value of response.user_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.user_id
     *
     * @param userId the value for response.user_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.title
     *
     * @return the value of response.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.title
     *
     * @param title the value for response.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.content
     *
     * @return the value of response.content
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.content
     *
     * @param content the value for response.content
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.message_id
     *
     * @return the value of response.message_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.message_id
     *
     * @param messageId the value for response.message_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.create_time
     *
     * @return the value of response.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.create_time
     *
     * @param createTime the value for response.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column response.update_time
     *
     * @return the value of response.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column response.update_time
     *
     * @param updateTime the value for response.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}