package cn.edu.shu.society.entity;

public class VoteTopicNumber {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.vote_topic_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long voteTopicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.vote_topic_vote_number
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long voteTopicVoteNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_topic_number.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_topic_number.id
     *
     * @return the value of vote_topic_number.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_topic_number.id
     *
     * @param id the value for vote_topic_number.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_topic_number.vote_topic_id
     *
     * @return the value of vote_topic_number.vote_topic_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getVoteTopicId() {
        return voteTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_topic_number.vote_topic_id
     *
     * @param voteTopicId the value for vote_topic_number.vote_topic_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setVoteTopicId(Long voteTopicId) {
        this.voteTopicId = voteTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_topic_number.vote_topic_vote_number
     *
     * @return the value of vote_topic_number.vote_topic_vote_number
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getVoteTopicVoteNumber() {
        return voteTopicVoteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_topic_number.vote_topic_vote_number
     *
     * @param voteTopicVoteNumber the value for vote_topic_number.vote_topic_vote_number
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setVoteTopicVoteNumber(Long voteTopicVoteNumber) {
        this.voteTopicVoteNumber = voteTopicVoteNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_topic_number.create_time
     *
     * @return the value of vote_topic_number.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_topic_number.create_time
     *
     * @param createTime the value for vote_topic_number.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_topic_number.update_time
     *
     * @return the value of vote_topic_number.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_topic_number.update_time
     *
     * @param updateTime the value for vote_topic_number.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}