package cn.edu.shu.society.entity;

public class VoteType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_type.id
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_type.type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_type.parent_type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    private String parentTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_type.create_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_type.update_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_type.id
     *
     * @return the value of vote_type.id
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_type.id
     *
     * @param id the value for vote_type.id
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_type.type_name
     *
     * @return the value of vote_type.type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_type.type_name
     *
     * @param typeName the value for vote_type.type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_type.parent_type_name
     *
     * @return the value of vote_type.parent_type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public String getParentTypeName() {
        return parentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_type.parent_type_name
     *
     * @param parentTypeName the value for vote_type.parent_type_name
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public void setParentTypeName(String parentTypeName) {
        this.parentTypeName = parentTypeName == null ? null : parentTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_type.create_time
     *
     * @return the value of vote_type.create_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_type.create_time
     *
     * @param createTime the value for vote_type.create_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_type.update_time
     *
     * @return the value of vote_type.update_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_type.update_time
     *
     * @param updateTime the value for vote_type.update_time
     *
     * @mbggenerated Tue Jul 12 16:48:15 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}