package cn.edu.shu.society.entity;

public class VoteSubjectResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.select_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Boolean selectResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.content_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private String contentResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.vote_subject_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long voteSubjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject_result.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.id
     *
     * @return the value of vote_subject_result.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.id
     *
     * @param id the value for vote_subject_result.id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.user_id
     *
     * @return the value of vote_subject_result.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.user_id
     *
     * @param userId the value for vote_subject_result.user_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.select_result
     *
     * @return the value of vote_subject_result.select_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Boolean getSelectResult() {
        return selectResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.select_result
     *
     * @param selectResult the value for vote_subject_result.select_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setSelectResult(Boolean selectResult) {
        this.selectResult = selectResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.content_result
     *
     * @return the value of vote_subject_result.content_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public String getContentResult() {
        return contentResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.content_result
     *
     * @param contentResult the value for vote_subject_result.content_result
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setContentResult(String contentResult) {
        this.contentResult = contentResult == null ? null : contentResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.vote_subject_id
     *
     * @return the value of vote_subject_result.vote_subject_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getVoteSubjectId() {
        return voteSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.vote_subject_id
     *
     * @param voteSubjectId the value for vote_subject_result.vote_subject_id
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setVoteSubjectId(Long voteSubjectId) {
        this.voteSubjectId = voteSubjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.create_time
     *
     * @return the value of vote_subject_result.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.create_time
     *
     * @param createTime the value for vote_subject_result.create_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject_result.update_time
     *
     * @return the value of vote_subject_result.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject_result.update_time
     *
     * @param updateTime the value for vote_subject_result.update_time
     *
     * @mbggenerated Sun Jul 03 18:10:29 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}