package cn.edu.shu.society.entity;

public class VoteSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.vote_subject_type_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long voteSubjectTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_subject.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.id
     *
     * @return the value of vote_subject.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.id
     *
     * @param id the value for vote_subject.id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.title
     *
     * @return the value of vote_subject.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.title
     *
     * @param title the value for vote_subject.title
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.vote_subject_type_id
     *
     * @return the value of vote_subject.vote_subject_type_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getVoteSubjectTypeId() {
        return voteSubjectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.vote_subject_type_id
     *
     * @param voteSubjectTypeId the value for vote_subject.vote_subject_type_id
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setVoteSubjectTypeId(Long voteSubjectTypeId) {
        this.voteSubjectTypeId = voteSubjectTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.create_time
     *
     * @return the value of vote_subject.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.create_time
     *
     * @param createTime the value for vote_subject.create_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_subject.update_time
     *
     * @return the value of vote_subject.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_subject.update_time
     *
     * @param updateTime the value for vote_subject.update_time
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}