package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.MessageType;
import java.util.List;

public interface MessageTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(MessageType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    MessageType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<MessageType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(MessageType record);
}