package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.Message;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    Message selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<Message> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(Message record);

    List<Message> selectByMessageTypeIdAndPassStatus(@Param("messageTypeId") Long messageTypeId, @Param("passStatusArr") boolean[] passStatusArr);

    Long selectCountByMessageTypeIdAndPassStatus (@Param("messageTypeId") Long messageTypeId, @Param("passStatusArr") boolean[] passStatusArr);

    int updateIsPassed(@Param("messageId") Long messageId,@Param("isPassed")  boolean isPassed);
}