package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.Response;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ResponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table response
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table response
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(Response record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table response
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    Response selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table response
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<Response> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table response
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(Response record);

    List<Response> selectByMessageId(@Param("messageId") Long messageId);
}