package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.VoteSubjectResult;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface VoteSubjectResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject_result
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject_result
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(VoteSubjectResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject_result
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    VoteSubjectResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject_result
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<VoteSubjectResult> selectAll();


    List<VoteSubjectResult> selectBySubjectIdAndUserId(Long voteSubjectId,Long userId);

    List<VoteSubjectResult> selectBySubjectId(Long voteSubjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_subject_result
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(VoteSubjectResult record);

    Long countVoteNumberByResultVoteItemId(Long resultVoteItemId);

    Long isHaveVoted(Long userId);
}