package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.VoteType;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface VoteTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(VoteType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    VoteType selectByPrimaryKey(Long id);

    String getParentTypeNameById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<VoteType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_type
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(VoteType record);
}