package cn.edu.shu.society.repository;

import cn.edu.shu.society.entity.VoteTopic;
import java.util.List;

public interface VoteTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_topic
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_topic
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int insert(VoteTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_topic
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    VoteTopic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_topic
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    List<VoteTopic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_topic
     *
     * @mbggenerated Thu Jun 23 22:16:17 CST 2016
     */
    int updateByPrimaryKey(VoteTopic record);
}